### ISSUE TITLE
website lost - is this project retired?

### ISSUE THREAD

**Issue by mysteriousplanet** [flapjack/omnibus-flapjack#110]
I presume this project is now retired?

I don't use this, but wandered across it on some other work, and found that the website no longer works.
It looks like the domain hasn't been renewed, maybe for up to a year ago now.

The last versions I can see on archive.org was 2023-03
https://web.archive.org/web/20230320195416/https://flapjack.io/

**Comment by auxesis** [comment]
@mysteriousplanet that's correct, you should consider Flapjack end of life.
