### ISSUE TITLE
Recommend Rakefile usage in README

### ISSUE THREAD

**Issue by Hobbsee** [flapjack/omnibus-flapjack#67]
The Rakefile makes building omnibus-flapjack a lot easier - the README should be tweaked to indicate that this is the case.

The env variables to set for the non-rakefile version are unclear, and likely out of date.

**Comment by jessereynolds** [comment]
The above exception is being tracked here: https://github.com/flapjack/flapjack/issues/757

**Comment by Hobbsee** [comment]
Given the number of variables we're passing through, i'm in favour of declaring that the params passed to omnibus are an implementation detail, and not adding it to the readme.  If someone actually wants to do a non-docker build, they can run the dry-run version, and copy/paste the commands.

That latter sentence should perhaps be documented.
