### ISSUE TITLE
Builds failing with "zlib is missing; necessary for building libxml2"

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#72]
```
USER DATA SCRIPT STARTING AT Tue Feb 10 03:26:33 UTC 2015
UPDATING omnibus-flapjack
From https://github.com/flapjack/omnibus-flapjack
   b8fe522..dd4e2fc  master     -> origin/master
 * [new branch]      readme-update -> origin/readme-update
Updating b8fe522..dd4e2fc
Fast-forward

...snip...

Fetching git://github.com/opscode/omnibus-software.git
Fetching git://github.com/Hobbsee/omnibus.git
Fetching gem metadata from https://rubygems.org/........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing mime-types 1.25.1
Installing mini_portile 0.6.2

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb 
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/ruby1.9.1
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build


Gem files will remain installed in /tmp/bundler20150210-1666-1wjwab1/nokogiri-1.6.6.2/gems/nokogiri-1.6.6.2 for inspection.
Results logged to /tmp/bundler20150210-1666-1wjwab1/nokogiri-1.6.6.2/gems/nokogiri-1.6.6.2/ext/nokogiri/gem_make.out
An error occurred while installing nokogiri (1.6.6.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.6.2'` succeeds before bundling.
```

```
ubuntu@ip-10-45-3-184:~/omnibus-flapjack$ find /usr -name *zlib*
/usr/src/linux-headers-3.13.0-32-generic/include/config/ubifs/fs/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/crypto/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/zlib
/usr/src/linux-headers-3.13.0-32-generic/include/config/squashfs/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/config/jffs2/zlib.h
/usr/src/linux-headers-3.13.0-32-generic/include/linux/zlib.h
/usr/src/linux-headers-3.13.0-32/lib/zlib_inflate
/usr/src/linux-headers-3.13.0-32/lib/zlib_deflate
/usr/src/linux-headers-3.13.0-32/include/linux/zlib.h
/usr/share/doc/zlib1g
/usr/share/ri/1.9.1/system/Zlib/zlib_version-c.ri
/usr/lib/ruby/1.9.1/x86_64-linux/zlib.so
/usr/lib/python3.4/encodings/zlib_codec.py
/usr/lib/python3.4/encodings/__pycache__/zlib_codec.cpython-34.pyc
/usr/lib/rsyslog/lmzlibw.so
/usr/lib/python2.7/encodings/zlib_codec.py
/usr/lib/python2.7/encodings/zlib_codec.pyc
```

**Comment by jessereynolds** [comment]
Fixed this by including zlib1g-dev package in the ami we're using

**Comment by asbjornenge** [comment]
@jessereynolds love it when people leave the solution for others to find. Thank you :+1:

**Comment by jessereynolds** [comment]
@asbjornenge :-) ... which project did you strike this one in?

**Comment by asbjornenge** [comment]
@jessereynolds https://github.com/Thibaut/devdocs actually, trying to build locally. Got it working eventually :+1: :smile:

**Comment by guaka** [comment]
What's an "ami" and how do I include zlib1g-dev in it? :)

**Comment by SarahKowalik** [comment]
@guaka, the AMI is what we use to build Flapjack cleanly and reproducibly on Amazon Web Services.  You don't need an AMI to build on your own machine - just install zlib1g-dev (or the equivalent package for your operating system), and you won't see this error.

**Comment by gessgallardo** [comment]
:+1:  @SarahKowalik thx!

**Comment by Heshuge** [comment]
for ubuntu: 

sudo apt-get install zlib1g-dev

worked for me

**Comment by JanisVepris** [comment]
Solution by @Heshuge worked for me on Ubuntu 15.10.

**Comment by rchennuri** [comment]
Thank you @Heshuge  , solution is worked for me on Ubuntu 14.4

**Comment by liuzxc** [comment]
thanks @Heshuge , it works for me!

**Comment by hastebrot** [comment]
Thanks. Needed this for Nokogiri on Ubuntu 14.04.

**Comment by thindiyeh** [comment]
for Redhat or Centos use #sudo yum install zlib-devel -y

**Comment by samnissen** [comment]
+1 @thindiyeh

**Comment by jiajielu** [comment]
@Heshuge worked for me on Ubuntu 12.04

**Comment by markpahulje** [comment]
RE: Fixed this by including zlib1g-dev package in the ami we're using
Installing zlib1g-dev, fixed install issue with nokogiri on Debian 8.4
Installed nokogiri RC2 using '_sudo gem install nokogiri -v 1.6.8.rc2_' which orginally complained about 'zlib is missing; necessary for building libxml2', which made no sense because libxml2 was present.  Many Thanks!!!! Hope this helps next person ;)

**Comment by eldersoares** [comment]
today, from the official github pages page: tells me to install jekyll; jekyll asks me for nokogiri 1.6.7.2; nokogir asks me for zlib. i find this page and install zlib1g-dev. i guess things are ok now. i guess this version is kinda outdated, right?

**Comment by yidingalan** [comment]
works for me on ubuntu 16.04

**Comment by planetrobbie** [comment]
works for me too on 16.04, hurrah and thanks.

**Comment by behroozam** [comment]
zlib is missing; necessary for building libxml2
needed for nokogiri or jemoji package . 
solution: sudo apt-get install zlib1g-dev

**Comment by Alfredo-Moreira** [comment]
How do you solve this for a OSX system? All i unfortunately see is Linux fixes :(

**Comment by ingokeck** [comment]
To install nokogiri on MacOS X is a nightmare. Some people have no issues on new out-of-the-box systems. All others try to find the one version that works. I finally got it working one day by manually setting the paths to the libraries it claimed it was not finding.

**Comment by jamespfinn** [comment]
For anyone who landed here because they ran into this issue on the Amazon Linux AMI, installint the zlib-devel package solved the problem for me.

**Comment by jbananas** [comment]
Ran into this on WSL while installing a Jekyll theme gem that depended on nokogiri.  sudo apt-get install zlib1g-dev fixed it right up

**Comment by penut85420** [comment]
thanks @r0zar, work for me on ubuntu 18.04

**Comment by leggiero** [comment]
Thanks @r0zar! Your solution workes for me on Ubuntu 20.04

**Comment by agc133** [comment]
@jessereynolds You are the man! Thank you for this solution.

**Comment by stevecondylios** [comment]
For me, I needed (needed the update line first)

```sh
apt-get update -y
apt-get install zlib1g-dev -y
```
