### ISSUE TITLE
Upload broken packages somewhere

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#83]
Package builds that fail the tests should be uploaded somewhere so they can be inspected. 

To a packages.flapjack.io bare file, or a 'broken' component in the repos perhaps

Include download link in build log

**Comment by Hobbsee** [comment]
A staging directory on s3 would be fine.  Perhaps we remove any packages matching the version and release at the end of the promote script so it doesn't get too big and unwieldy.
