### ISSUE TITLE
Name docker containers so we can support multiple concurrent builds

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#87]
Currently we don't name the containers and use something like `docker ps -a | head -1` to determine the container we we just ran the build in. We then use that container ID to copy the built package out of the dead containers hands. 

We could name the container and then use that as a reference, then we should be able to kick off all the builds in parallel and achieve shorter build time overall. (Build time is currently about 2 hours for the 4 distro/release combos we currently support.)

An alternative might be to declare a volume in order to have the package appear in the docker host's filesystem at a known location, to avoid the step of copying the package out of the dead container.

**Comment by Hobbsee** [comment]
> We could name the container and then use that as a reference, then we should be able to kick off all the builds in parallel and achieve shorter build time overall. (Build time is currently about 2 hours for the 4 distro/release combos we currently support.)

While we’d be able to do the builds in parallel, the precise/trusty/debian publishing has to be run sequentially.

Of course, if we switch to packagecloud.io, we can get rid of aptly, this issue goes away.

**Comment by jessereynolds** [comment]
> While we’d be able to do the builds in parallel, the precise/trusty/debian publishing has to be run sequentially.

Oh right, because of the local copy of aptly repo stuff, I forgot about that part of it. I suppose they could be namespaced per build so they don't conflict. The locking around updates to the repos on s3 would get a good working out.
