### ISSUE TITLE
New hiredis version causes omnibus-flapjack build to fail

### ISSUE THREAD

**Issue by bryanyork** [flapjack/omnibus-flapjack#94]
It looks like hiredis released a new version, and the flapjack build fails on it
cc -o examples/hiredis-example -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb    -I. examples/example.c libhiredis.a

Error:

    In file included from examples/example.c:5:
./hiredis.h:158: error: expected identifier or '(' before numeric constant
./hiredis.h:160: warning: no semicolon at end of struct or union
make: *** [hiredis-example] Error 1

Looks like we just grab master every time we build
"if [ ! -d hiredis ] ; then git clone https://github.com/redis/hiredis.git hiredis ; fi && " +

Can we make sure to specify a tag to checkout instead?

**Comment by Hobbsee** [comment]
Thanks @bryanyork, I've fixed this up now.
