### ISSUE TITLE
flapjack master builds fail at ncurses - undefined method ppc64le

### ISSUE THREAD

**Issue by jessereynolds** [flapjack/omnibus-flapjack#97]
<code>
/var/lib/gems/1.9.1/bundler/gems/omnibus-software-4c7d963f222e/config/software/ncurses.rb:85:in `block in evaluate': undefined method `ppc64le?' for #<Omnibus::Builder (Cleanroom)> (NoMethodError)
</code>

**Comment by jessereynolds** [comment]
Eg full build log: http://is.gd/wby5st

**Comment by Hobbsee** [comment]
Looks to be https://github.com/chef/omnibus-software/issues/413, updated my version of omnibus.

**Comment by Hobbsee** [comment]
Fixed.  This has broken versioning, which I've put in a tentative fix for, and am testing out now.

**Comment by Hobbsee** [comment]
That now also works.
